/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osvr_util_OSVR_Button */

#ifndef _Included_osvr_util_OSVR_Button
#define _Included_osvr_util_OSVR_Button
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osvr_util_OSVR_Button
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_util_OSVR_1Button_initializeNative
  (JNIEnv *, jobject);

/*
 * Class:     osvr_util_OSVR_Button
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_osvr_util_OSVR_1Button_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
